# Generated by Django 4.1.1 on 2022-09-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='heure_de_fin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
